apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: crossplane-test-bucket-fahd
  namespace: crossplane-system
spec:
  forProvider:
    acl: private
    locationConstraint: ap-southeast-2
    versioningConfiguration:
      status: Enabled
  providerConfigRef:
    name: aws-provider-config
  providerRef:
    name: aws-provider-config